{
  "guid": "39842e94-d740-45dd-b7b1-0e5d0ffae4f0",
  "componentGuid": "dcba9337-2417-46f4-82ed-27cfd6bb5e4b",
  "componentName": "Test",
  "plateQualityControlDatas": [
    {
      "platePairGuid": "d1834ce8-4bda-44a0-ad97-b277d037dcfe",
      "areaMethod": "Gross",
      "zeroTolerancePolygon": {
        "vertices": []
      },
      "jointStressIndex": 0.0,
      "rotationToleranceMin": -10.0,
      "rotationToleranceMax": 10.0,
      "contactAreas": [
        {
          "memberGuid": "a9f7fcf8-ea8d-46e2-9024-f30fe02bc814",
          "memberName": "B1",
          "requiredTeeth": 52,
          "requiredArea": 24.0,
          "jointStressIndex": 0.95
        }
      ]
    }
  ]
}